:post-date: 04-08-2008

== Endorsement:: Gentto Linux on my AMD 64 X2 4200+ Worksation

_Posted on {post-date}_

Last weekend I’ve found some time to build a linux system for my home workstation (until then I only used a Win XP Installation). After my first tries to reinstall the system with a ubuntu (7.10) installation a view months earlier (a year before there was a Debian/unstable version running on it). I now decided to use a distribution which is not so much “mainstream”. So first I played around with Open Solaris from Sun but sadly, in my opinion, it is an to early release and there are much things I like to use on my Linux desktop which are not supported in the current release. So finally my decision was to use Gentoo. I had planned to use it some years ago, but in that time I thought, that my Unix skills are to low to make it work…

First thing what I tried was the Installation by using a Gentoo live cd. Works fine but can’t boot the system… terrible thing… than I decided to install with minimal cd. I downloaded the i386 generic cd. But during installation decided to install a 64Bit System (in spite of my bad experience with Ubuntu 64 Bit). So first problem I got was that the x386 chroot command from cd wouldn’t work with the 64 Bit system. So I had to download the image for the 64 Bit version and then all was fine. Like a terrible Gentoo beginner I choosed much use flag I thought to need xD so my Installation of the whole system required more or less 28 hours x) But now it works an I must say the system is very cool. Its so small and fast and not much unused applications are installed like in Ubuntu. So I will test it and when it works nice in productive I will kill my laptops Ubuntu System and give him a Gentoo too xD

P.s. Regards to my friend Moritz, who inspired me to use Gentoo…