:post-date: 10-09-2008

== Recommendations to read (Part 1)

_Posted on {post-date}_

First of all there is the new book from my mum. Its called 'Raubkind' and written in german. Here is the description of this book (currently only in german):

____
Die Fantasie des Protagonisten Jakob schafft Handlungen, vernetzt Beziehungen oder lässt sie bröckeln, bindet oder entbindet Schicksale. "Raubkind" ist das Puzzle-Buch dieses seelenfrustrierten Beobachters, der sich in den virtuellen Lebensgeschichten der Anderen impliziert, um sich jedes Mal neu zu erfahren und korrigieren; die Geschichte eines meist sukzessiv (hinein)gleitenden Ichs mit mehreren Stimmen, Namen und Biografien, knappe Anatomie menschlicher/gesellschaftlicher Unvollkommenheit. Der mit dem Debütpreis des Ludwigsburger Pop-Verlags für 2008 ausgezeichnete Erstlingsroman der Lyrikerin und Prosaautorin Barbara-Marie Mund ist ein Szenario existentieller Sehnsucht nach dem verlorenen Etwas, in einem stetigen Wechselspiel von abgründiger Wirklichkeit und Projektion, von Schatten, Irrlichtern und Irrkreisen. Francisca Ricinski-Marienfeld
____

At that time I don't have read the book but I will do it very soon, and then I will write something about it and how I find it. If you wanna get it here is the link:
link:http://www.amazon.de/Raubkind-Roman-Barbara-M-Mundt/dp/3937139583/ref=sr_1_1?ie=UTF8&amp;s=books&amp;qid=1220954576&amp;sr=8-1[Raubkind :: Barbara Mundt :: Pop, Traian^]

The second book is from my lovely little sister Mareike. I've read it and must say this is one of the best books I've read in the last time. But maybe I am a little bit jaundiced, cause I am the brother, so you have to deside. The description of the book (also in german):
____
Fünf Jahre Leben auf der Straße, und dann zu Pflegeeltern. Kann das überhaupt gut gehen? Marie-Luna ist 16 Jahre alt und nun soll sie plötzlich all ihre Freiheiten aufgeben, all ihre Freunde von heute auf morgen verlassen und ein völlig neues Leben beginnen. Ein langwieriger Prozess des Umdenkens beginnt. Was bedeutet Freiheit überhaupt?Und wo soll dieses Leben eigentlich hinführen? Marie-Luna muss eine Entscheidung treffen, doch der Weg dahin ist steinig und nicht selten schmerzhaft.
Was bleibt ist der Traum vom fliegen und die Suche nach der wirklichen, grenzenlosen Freiheit[...]

[...] Das sollte nun also meine neue "Familie" sein. Eine Frau, die mir als Maggy vorgestellt wurde, und ein Mann namens Jon. Ich war wirklich begeistert. Seit sieben Jahren hatte ich mein Leben nun mehr oder weniger alleine gemeistert und jetzt mit 16 Jahren, wo ich wirklich gut darauf verzichten konnte, sollte ich das erste Mal in meinem Leben eine Familie haben.
"Und das ist Marie- Luna", schloss Bergmann, mein "Bewährungshelfer", die Vorstellungsrunde und deutete auf mich. Marie-Luna – wie das klang. So hatte mich seit einer Ewigkeit keiner mehr genannt. Bergmann verabschiedete sich und ich folgte meinen künftigen Pflegeeltern widerwillig ins Haus. "Dann wollen wir dir mal dein Zimmer zeigen, damit du deine Sachen abstellen und dir etwas anderes anziehen kannst, Luna – du hast doch nichts dagegen, wenn ich dich so nenne, oder?" "Schon okay", murmelte ich. Wie kam sie eigentlich darauf, dass ich mir etwas anderes anziehen wollte? Sie zeigte mir mein Zimmer, das sich im ersten Stock des Hauses befand, und forderte mich auf, doch runter in die Küche zu kommen, nachdem ich mich ein wenig umgesehen hätte, damit wir gemeinsam zu Mittag essen könnten[...]
____

And if you want you can get it at 
link:http://www.iatros-verlag.de/Kinder/Jugend/Frei-wie-ein-Zugvogel--92.html?XTCsid=2f83caf69f6b099a537d66ee4e6d5a41[Frei wie ein Zugvogel :: Mareike Rumpf :: Iatros-Verlag^]
