:site-date: 14-07-2008

== My cousin is under the 'cap'...

_Posted on {site-date}_

… transfering german sayings into english roxx 🙂 Jear last weakend we (Kim, Rainer, Kerstin and me) were at the wedding of my cousin Anne. I think it was the loveliest wedding were I ever was invited (ok, that aren’t so much but I think for the coming weddings it will be hard to beat that). But let me start on the beginning.

I started in Mannheim at 5:33 pm and had much luck because there was an ICE accident on Thursday evening (I think it was there, maybe it was ealier) and much of the ICE’s coming from Cologne has a delay. So even the ICE what I decided to use. But my luck was, that the ICE which was schedduled for 16.33 had one hour delay so it arrives when I was at Manheim main station 🙂 It was a little bit cramed but I was in and started to go to Ulm. Where I arrived at ca. 7.13 pm. Sadly I missed my follow up train that should bring me to Herbrechtingen. So I had to wait for 45 minnutes. When I was there my cousin Florian picks me up there an we drove to the hotel where I had booked a room. At the evening we were in a pizzeria in the same town (What a funny evening 😀 don’t give Rainer a flapper). On satuarday was the wedding. So after breakfirst we drove to the church in Herbrechtingen.

I was really suprised about the divine service (catolic) the pastor was very unformal and acquires us often to laugh 🙂 Its not so often (in my opinion), that a pastor is able to make such a funny thing. After church the party starts. I’m not willing to tell all the details but I must repeat myself, this party was a lot of fun. Much cute people and a pleasant bridal couple makes the evening perfect.

Here are some pictures from the day:

… pictures will follow soon …

The party ends up at night until 4 am, so on sunday morning (we had to stand up at 10 am for breakfirst – I made it at 10.30am 🙂 ) we was all very weary…

So after all I have to say: Good luck and much Children for you: Anne and Jochen 😉